# fly.toml app configuration file generated for vallorscan on 2026-06-28T11:14:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vallorscan'
primary_region = 'fra'

[build]

[env]
  DB_PATH = '/data/vallorscan.sqlite'
  HOST = '0.0.0.0'
  PORT = '8080'

[[mounts]]
  source = 'vallorscan_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
